import type { Metadata } from "next";
import { roboto } from "@/ui/fonts";
import "./globals.css";
import Navbar from "@/ui/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/ui/footer/footer";
import Button from "@/ui/buttons/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Javier Pardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  chat,
}: {
  children: React.ReactNode;
  chat: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          defaultTheme="system"
          attribute="data-theme"
          disableTransitionOnChange>
          <header>
            <Navbar>
              <Button href={"#"} chatChildren={chat} />
              {/* <span>Chat</span>
              </Button> */}
            </Navbar>
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
