import type { Metadata } from "next";
import { roboto } from "@/ui/fonts";
import "./globals.css";
import Navbar from "@/ui/navbar/navbar";

export const metadata: Metadata = {
  title: "Javier Pardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
