import type { Metadata } from "next";
import { roboto } from "@/ui/fonts";
import "./globals.css";
import Navbar from "@/ui/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Javier Pardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          defaultTheme="system"
          attribute="data-theme"
          disableTransitionOnChange>
          <header>
            <Navbar />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
